#!/bin/sh
set -e
echo "-------------------------------------------------------------"
echo "Cleanup {{ parts.buildout.directory }}/parts/assets_releases/*"
echo "-------------------------------------------------------------"
rm -f {{ parts.buildout.directory }}/parts/assets_releases/*.gz
echo "-------------------------------------------------------------"
filename=auction_assets_`git rev-parse --abbrev-ref HEAD`_`date -u +"%Y-%m-%dT%H:%M:%SZ"`.tar.gz
echo "Prepare $filename"
echo "-------------------------------------------------------------"
tar -zcvf {{ parts.buildout.directory }}/parts/assets_releases/$filename -C {{ parts.buildout.directory }}/parts/www .
echo "-------------------------------------------------------------"
echo "Upload $filename to dist server: op@dist.qg:/{{parts.project.resource_name}}_assets"
echo "-------------------------------------------------------------"
server="op@dist.qg"
destiny="{{parts.project.resource_name}}_web_assets"
src="{{ parts.buildout.directory }}/parts/assets_releases/$filename"
ssh "$server" "mkdir -p $destiny" && scp "$src" "$server:$destiny"
echo "-------------------------------------------------------------"
echo "Finished"

