#!/bin/sh
set -e
echo "-------------------------------------------------------------"
echo "Cleanup {{ parts.buildout.directory }}/parts/assets_releases/*"
echo "-------------------------------------------------------------"
rm -f {{ parts.buildout.directory }}/parts/assets_releases/*.gz
echo "-------------------------------------------------------------"
tag=`git rev-parse --abbrev-ref HEAD`_`date -u +"%Y_%m_%dT%H_%M_%SZ"`
filename=$tag".tar.gz"
cd {{ parts.buildout.directory }}/src/openprocurement.auction.js
git tag $tag
git push origin $tag
cd {{ parts.buildout.directory }}/src/openprocurement.auction.esco-js
git tag $tag
git push origin $tag
cd {{ parts.buildout.directory }}
echo "Prepare $filename"
echo "-------------------------------------------------------------"
tar -zcvf {{ parts.buildout.directory }}/parts/assets_releases/$filename -C {{ parts.buildout.directory }}/parts/www .
echo "-------------------------------------------------------------"
echo "Upload $filename to dist server: op@dist.qg:/{{parts.project.resource_name}}_assets"
echo "-------------------------------------------------------------"
server="op@dist.qg"
destiny="{{parts.project.resource_name}}_web_assets"
src="{{ parts.buildout.directory }}/parts/assets_releases/$filename"
ssh "$server" "mkdir -p $destiny" && scp "$src" "$server:$destiny"
echo "-------------------------------------------------------------"
echo "Finished"

