#!/bin/sh
set -e
echo "-------------------------------------------------------------"
echo "Cleanup {{ parts.buildout.directory }}/parts/lua_releases/*"
echo "-------------------------------------------------------------"
rm -f {{ parts.buildout.directory }}/parts/lua_releases/*.gz
echo "-------------------------------------------------------------"
filename=auction_lua_releases_`git rev-parse --abbrev-ref HEAD`_`date -u +"%Y-%m-%dT%H:%M:%SZ"`.tar.gz
echo "Prepare $filename"
echo "-------------------------------------------------------------"
tar -zcvf {{ parts.buildout.directory }}/parts/lua_releases/$filename -C {{ parts.buildout.directory }}/resty_modules/lualib .
echo "-------------------------------------------------------------"
echo "Upload $filename to dist server: prozorro@dist.qg:/{{parts.project.resource_name}}_lua_releases"
echo "-------------------------------------------------------------"
server="prozorro@dist.qg"
destiny="{{parts.project.resource_name}}_lua_releases"
src="{{ parts.buildout.directory }}/parts/lua_releases/$filename"
ssh "$server" "mkdir -p $destiny" && scp "$src" "$server:$destiny"
echo "-------------------------------------------------------------"
echo "Finished"

