#!/bin/bash
set  -x
if [ -f ~/.bash_profile ]; then
     .  ~/.bash_profile
fi
/usr/bin/sleep 10
/usr/bin/echo "Start replication"
HOSTNAME=`/usr/bin/hostname`
while ! /usr/bin/curl -s -H 'Content-Type:application/json' -XPOST  -d "{\"source\": \"{{ source }}\", \"target\": \"{{ target }}\", \"continuous\": true, \"create_target\": true}" {{ db_url }}; do /usr/bin/sleep 2; /usr/bin/echo "Re-try to start replication"; done
/usr/bin/echo "Replication started"